config/routes.rb
# frozen_string_literal: true

require 'constraints/post_route'

Rails.application.routes.draw do
  root 'pages#home'

  constraints(PostRoute) do
    get '/:parent_slug', to: 'posts#show', as: :parent_post
    get '/:parent_slug/:child_slug', to: 'posts#show', as: :child_post
  end

  get '/mounted_to_root', to: 'pages#mounted_to_root'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  before_destroy :check_if_post_is_destroyable

  belongs_to :parent, class_name: 'Post', optional: true
  has_many(
    :children,
    class_name: 'Post',
    dependent: :nullify,
    foreign_key: :parent_id,
    inverse_of: :parent
  )
  has_many :sections, dependent: :destroy
  belongs_to :section, optional: true

  scope :published, -> { where(published: true) }
  scope :parents, -> { where(parent_id: nil) }
  scope :sectionless, -> { where(section_id: nil) }

  def parent?
    parent_id.nil?
  end

  private

  def check_if_post_is_destroyable
    destroyable = children.blank? && sections.blank?
    return true if destroyable

    errors.add(:base, 'You may not delete this Parent Post.')

    # Returning false in Active Record and Active Model callbacks
    # will not implicitly halt a callback chain starting from Rails 5.1
    throw :abort
  end
end

# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text
#  position   :integer
#  published  :boolean          default(FALSE), not null
#  slug       :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  parent_id  :bigint
#  section_id :bigint
#
# Indexes
#
#  index_posts_on_parent_id   (parent_id)
#  index_posts_on_section_id  (section_id)
#  index_posts_on_slug        (slug)
#
# Foreign Keys
#
#  fk_rails_...  (parent_id => posts.id)
#  fk_rails_...  (section_id => sections.id)
#

app/models/section.rb
# frozen_string_literal: true

class Section < ApplicationRecord
  has_many :posts, dependent: :nullify
  belongs_to :post, optional: true
end

# == Schema Information
#
# Table name: sections
#
#  id         :bigint           not null, primary key
#  name       :string
#  position   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint
#
# Indexes
#
#  index_sections_on_post_id  (post_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    @posts = Post.published.parents.order(position: :asc)
  end

  def mounted_to_root; end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  def show
    @post = PostFinder.new(params).call
    @toc = TocBuilder.new(@post).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedPosts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <h1>Nested Posts</h1>

    <% unless current_page?(root_path) %>
      <%= link_to 'Home', root_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if @posts.any? %>
  <nav>
    <ul>
      <% @posts.each do |post| %>
        <li>
          <%= link_to post.title, parent_post_path(post.slug) %>
        </li>
      <% end %>
    </ul>
  <nav>
<% end %>

app/views/posts/_post.html.erb
<main>
  <h2><%= @post.title %></h2>

  <article>
    <p><%= @post.body %></p>
  </article>
</main>

app/views/posts/_toc.html.erb
<% if toc&.any? %>
  <nav class='toc'>
    <ul>
      <% toc.map do |toc_item| %>
        <% if toc_item[:type] == 'section' %>
          <li>
            <h3><%= toc_item[:name] %></h3>

            <ul>
              <% toc_item[:posts].map do |post| %>
                <li>
                  <h4><%= link_to post[:name], post[:link] %></h4>
                </li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <h4><%= link_to toc_item[:name], toc_item[:link] %></h4>
        <% end %>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/posts/show.html.erb
<div class=post-show>
  <%= render @post %>
  <%= render partial: 'toc', locals: { toc: @toc } %>
</div>